version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    command: ["/bin/sh", "-c", "service cron start && php-fpm"]

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_vendas
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    command: php artisan queue:work --tries=3
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
